### ISSUE TITLE
Update v.1.3

### ISSUE THREAD

**Issue by Xawery94** [Przemro/Szablon-misji#111]
Lista rzeczy do zrobienia dla update v1.3:

Dodanie nowych frakcji:
- [x] Rosja Cyfra 2035, 
- [x] BAF, 
- BW:
  - [x] Desert,
  - [x] Woodland, 
- USMC: 
  - [x] Desert,
  - [x] Woodland, 
- Polskie Siły Zbrojne:
  - [x] Desert,
  - [x] Woodland.

Dodanie klas i wyposażenia dla SF:
- [x] Rosja Cyfra 2035,
- [ ] BAF,  
- BW:
  - [x] Desert,
  - [x] Woodland, 
- USMC: 
  - [ ] Desert,
  - [ ] Woodland, 
- Polskie Siły Zbrojne:
  - [x] Desert,
  - [x] Woodland.

DAC:
- [x] Dodanie kompatybilności z Zeus-em,
- Aktualizacja jednostek DAC:
  - [x] Dodanie jednostek SP (RKM) do DAC_creator,
  - Dodanie jednostek DAC:
    - [x] PSZ,
    - [x] Takistańska Armia,
    - [x] BW,
    - [x] US Army,
    - [x] USMC.

Pozostałe:
- [x] Usprawnienie AI (opcjonalne) #100
- [ ] Dodanie brakującego wyposażenia dla logistyki #108 
- [x] Dodanie GPS-u dla co-pilota #112 
- [x] Dodanie nowych definicji wywołań plecaka dla dowódcy pojazdu
- [x] Dodanie nowych obozów DAC
- [x] Drobne zmiany w skryptach szablonu (dodanie nowych definicji dla przedmiotów)
- [x] Złe flary dla USMC #114
- [x] Latarki dla M4A1 #115

**Comment by Xawery94** [comment]
Aktualizacja szablonu do wersji 1.3
